### ISSUE TITLE
Zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by mxbi** [anlthms/sp-2016#2]
When running `run.sh`, I get the following error:

```
(.venv2)mirek@eru:~/sp-2016$ ./run.sh ../mel/ ../
+ '[' -f ../mel//prepdone ']'
+ echo ../mel//prepdone exists. Skipping prep...
../mel//prepdone exists. Skipping prep...
++ seq 0 15
+ for elec in '`seq 0 15`'
+ echo Electrode 0...
Electrode 0...
+ ./clear.sh ../mel/
removed ‘../mel//train_1/tain-index.csv’
removed ‘../mel//train_1/eval-index.csv’
removed ‘../mel//train_1/full-index.csv’
removed directory: ‘../mel//train_1/full-ingested’
removed ‘../mel//train_2/full-index.csv’
removed directory: ‘../mel//train_2/full-ingested’
removed ‘../mel//test_1/test-index.csv’
removed ‘../mel//test_2/test-index.csv’
++ seq 1 3
+ for subj in '`seq 1 3`'
+ train_dir=../mel//train_1/
+ '[' '!' -e ../mel//train_1/ ']'
+ echo Processing subject 1...
Processing subject 1...
+ ./model.py -e 16 -w ../mel//train_1/ -r 0 -z 64 -v --no_progress_bar -elec 0 -out ../
2016-09-20 17:57:45,596 - neon.backends.nervanagpu - INFO - Initialized NervanaGPU
2016-09-20 17:57:45,598 - neon.backends - INFO - Backend: gpu, RNG seed: 0
2016-09-20 17:57:45,598 - neon.util.argparser - INFO - Command Line Args:   -e 16 -w ../mel//train_1/ -r 0 -z 64 -v --no_progress_bar -elec 0 -out ../
Defaults:
  --serialize:       0
  --history:         1
  --backend:         gpu
  --device_id:       0
  --max_devices:     4
  --rounding:        False
  --datatype:        f32

Traceback (most recent call last):
  File "./model.py", line 42, in <module>
    tain_idx, test_idx = indexer.run(data_dir, pattern, testing=args.test_mode)
  File "/home/mirek/sp-2016/indexer.py", line 55, in run
    hours = range(segms.min(), segms.max() + 1, 6)
  File "/home/mirek/Soft/neon/.venv2/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
```

The ../mel/ directory has the following structure:

``` .
├── prepdone
├── sample-submission.csv
├── test_1
├── test_1.zip
├── test_2
├── test_2.zip
├── test_3
├── test_3.zip
├── train_1
├── train_1.zip
├── train_2
├── train_2.zip
├── train_3
└── train_3.zip
```

The folders for train_1, test_1 etc contain the untouched unzipped mat files.

Any ideas on how I can fix this?

**Comment by mxbi** [comment]
The fix was to remove the `prepdone` file. I'm not sure how it got there, since I've never seen the prep messages appear any other time I've run it.

Maybe there should be a check added to count the number of wav files?

**Comment by anlthms** [comment]
@mxbi, that's a good suggestion.
