### ISSUE TITLE
Audio support not built-in. Please install the pre-requisites and re-run the installer.

### ISSUE THREAD

**Issue by ternaus** [anlthms/sp-2016#5]
Ubuntu 16.04
Cuda 8
neon 1.6.0

ffmpeg installed

``` bash
Defaults:
  --serialize:       0
  --history:         1
  --log_token:       
  --backend:         gpu
  --device_id:       0
  --max_devices:     1
  --rounding:        False
  --datatype:        f32

Exception at src/api.hpp:51 Audio support not built-in. Please install the pre-requisites and re-run the installer.
Traceback (most recent call last):
  File "./model.py", line 55, in <module>
    repo_dir=data_dir, **common)
  File "/home/vladimir/anaconda2/envs/neon/lib/python2.7/site-packages/neon-1.6.0-py2.7.egg/neon/data/dataloader.py", line 170, in __init__
    self.start()
  File "/home/vladimir/anaconda2/envs/neon/lib/python2.7/site-packages/neon-1.6.0-py2.7.egg/neon/data/dataloader.py", line 250, in start
    raise RuntimeError('Failed to start data loader.')
```

**Comment by ternaus** [comment]
Solved by defining PKG_CONFIG_PATH variable before installation

`export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig`

**Comment by wujy2015** [comment]
what package do you mean by installation?
